export const ATTACHMENT_SERVER_TIMEOUT = 'ATTACHMENT_SERVER_TIMEOUT';
export const ATTACHMENT_SERVER_MAX_REDIRECT = 'ATTACHMENT_SERVER_MAX_REDIRECT';
export const ATTACHMENT_SERVER_URL = 'ATTACHMENT_SERVER_URL';
