name: Build
on:
  push:
    branches:
      - main
      - develop
      - workflow_test
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run Install Dependences
        run: npm i
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
  unit-test:
    name: Unit Test Jest
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Run All Unit Tests
        run: npm run test:cov
      - uses: actions/cache@v3
        id: build-unit-test
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: actions/upload-artifact@v3
        with:
          name: reports-unit-test
          path: coverage/*
    # e2e-testing:
    # name: E2E Testing
    # needs: build
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #     with:
    #       fetch-depth: 0
    #   - name: Create .env file
    #     uses: SpicyPizza/create-envfile@v1.2
    #     with:
    #       envkey_URL_API_REST_BOT: ${{secrets.URL_API_REST_BOT}} #API REST SKY BOT
    #       envkey_TZ: ${{secrets.TZ}} # TIME ZONE
    #       envkey_GOOGLE_CLIENT_EMAIL: ${{secrets.GOOGLE_CLIENT_EMAIL}} # GOOGLE DIALOGFLOW PROPERTIES
    #       envkey_GOOGLE_PRIVATE_KEY: ${{secrets.GOOGLE_PRIVATE_KEY}}
    #       envkey_GOOGLE_PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
    #       envkey_DF_LANGUAGE_CODE: ${{secrets.DF_LANGUAGE_CODE}}
    #       envkey_FB_PAGE_TOKEN: ${{secrets.FB_PAGE_TOKEN}}  #FACEBOOK PROPERTIES
    #       envkey_FB_VERIFY_TOKEN: ${{secrets.EMAIL_PORT}}
    #       envkey_FB_APP_SECRET: ${{secrets.FB_APP_SECRET}}
    #       envkey_FB_API_URL: ${{secrets.FB_API_URL}}
    #       envkey_AUTH0_DOMAIN: ${{secrets.AUTH0_DOMAIN}} # AUTH0 PROPERTIES
    #       envkey_AUTH0_CLIENT_ID: ${{secrets.AUTH0_CLIENT_ID}}
    #       envkey_AUTH0_CLIENT_SECRET: ${{secrets.AUTH0_CLIENT_SECRET}}
    #       envkey_AUTH0_AUDIENCE: ${{secrets.AUTH0_AUDIENCE}}
    #       envkey_AUTH0_REFRESH_TOKEN_MS: ${{secrets.AUTH0_REFRESH_TOKEN_MS}}
    #       envkey_REDIS_HOST: ${{secrets.REDIS_HOST}} # REDIS DATABASE PROPERTIES
    #       envkey_REDIS_PORT: ${{secrets.REDIS_PORT}}
    #       envkey_REDIS_USERNAME: ${{secrets.REDIS_USERNAME}}
    #       envkey_REDIS_PASSWORD: ${{secrets.REDIS_PASSWORD}}
    #       envkey_REDIS_CACHE_DURATION: ${{secrets.REDIS_CACHE_DURATION}}
    #       envkey_DATE_PATTERN: ${{secrets.DATE_PATTERN}} # LOGGER PROPERTIES
    #       envkey_APP_NAME: ${{secrets.APP_NAME}}
    #       envkey_MAX_SIZE: ${{secrets.MAX_SIZE}}
    #       envkey_MAX_DAYS: ${{secrets.MAX_DAYS}}
    #       envkey_LOG_FOLDER: ${{secrets.LOG_FOLDER}}
    #       envkey_TIMESTAMP_FORMAT: ${{secrets.TIMESTAMP_FORMAT}}
    #       env_key_LOGSTASH_ENABLED: ${{secrets.LOGSTASH_ENABLED}}
    #       directory: ${{ github.workspace }}
    #       file_name: .env
    #       fail_on_empty: false
    #   - uses: actions/setup-node@v3
    #     with:
    #       node-version: 16
    #   - uses: actions/cache@v3
    #     id: restore-build
    #     with:
    #       path: ./*
    #       key: ${{ github.sha }}
    #   - name: Run All E2E Test
    #     run: npm run test:e2e:cov
    #   - uses: actions/upload-artifact@v3
    #     with:
    #       name: reports-e2e-test
    #       path: coverage-e2e/*
  sonarcloud:
    name: SonarCloud
    needs: [build, unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v3
        id: build-unit-test
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: actions/download-artifact@v3
        with:
          name: reports-unit-test
          path: coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
